global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['collector:8888']
        labels:
          service: 'collector'

  - job_name: 'mock-upstream'
    scrape_interval: 5s
    static_configs:
      - targets: ['mock-upstream:8081']
        labels:
          service: 'mock-upstream'

  - job_name: 'nr-ingest'
    scrape_interval: 5s
    static_configs:
      - targets: ['nr-ingest:8889']
        labels:
          service: 'nr-ingest'

  - job_name: 'workload-generator'
    scrape_interval: 5s
    static_configs:
      - targets: ['workload-generator:9464']
        labels:
          service: 'workload-generator'
